# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b993bda5cec9bf972dd1ef2aa564a76a9365cd650214fa88f7d7d1f8cb3492627dc6d815af7375af22faa554a652a1b71668ab6719e410bbbb9b3646f34af3c8

test:
  secret_key_base: e0a8abc6ff9481366473a2d8b76385f894cbb55b135ab206772ba7f168b6b39e3fb7fffb7e463316bffe59a3b9397f895621a42893f2a9aa7e69bb513a16bfb0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
